w="python"
# print(w[:]) 
# print(w[0:]) 
# print(w[0:6]) 
# print(w[0:0]) 
# print(w[0:1]) 
# print(w[0:2]) 
# print(w[0:3]) 
# print(w[0:4]) 
# print(w[0:5]) 
# print(w[0:6]) 
# print(w[0:7]) 
# print(w[0:99]) 
# print(w[0:0]) 
# print(w[3:2]) 
# print(w[5:3]) 
# print(w[0:-1]) 
# print(w[0:-2]) 
# print(w[0:-3]) 
# print(w[0:-4]) 
# print(w[0:-5]) 
# print(w[0:-6]) 
# print(w[0:-7]) 

# r="python"
# print(r[2:5]) 
# print(r[3:4]) 
# print(r[5:2]) 
# print(r[5:5]) 

# y="python"
# print(y[-1:-6])
# print(y[2:-5])
# print(y[-6:])

# c="python"
# print(c[ : : ]) 
# print(c[0 : : 1]) 
# print(c[ : :2]) 
# print(c[ : :3]) 
# print(c[ : :4]) 
# print(c[ : :5]) 
# print(c[ : :6]) 
# print(c[: : -1]) 
# print(c[:  :-2]) 
# print(c[ : :-3]) 
# print(c[ : :-4]) 
# print(c[ : :-5]) 
# print(c[ : :-6]) 
# print(c[1: : ]) 
# print(c[2: : ]) 
# print(c[3: : ]) 
# print(c[4: : ]) 
# print(c[5: : ]) 
# print(c[6: : ]) 
# print(c[1: 6: ]) 
# print(c[2: 5: ]) 
# print(c[3: 4: ]) 
# print(c[4: 3: ]) 
# print(c[5: 2: ]) 
# print(c[6: 1: ]) 
